<a href="https://colab.research.google.com/github/RadarGem/RadarGem/blob/main/NumPy_Array_and_Vectorization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#convention for importing numpy
import numpy as np

arr = [6,7,8,9]
print(type(arr)) #prints <class 'list'>
a = np.array(arr)
print (type(a))
print(a.shape)
print(a.ndim)
b = np.array([[1,2,3],[4,5,6]])
print (b)
print(b.ndim)
print(b.shape)
c=np.array([[9.0,8.0,7.0],[1.0,2.0,3.0]])
d=np.array([[4.0,5.0,6.0],[9.0,8.0,7.0]])
print(c+d)
print (c*d)
print(5/d)
print(c**d)

<class 'list'>
<class 'numpy.ndarray'>
(4,)
1
[[1 2 3]
 [4 5 6]]
2
(2, 3)
[[13. 13. 13.]
 [10. 10. 10.]]
[[36. 40. 42.]
 [ 9. 16. 21.]]
[[1.25       1.         0.83333333]
 [0.55555556 0.625      0.71428571]]
[[6.56100e+03 3.27680e+04 1.17649e+05]
 [1.00000e+00 2.56000e+02 2.18700e+03]]


In [ ]:
c+d
c*d
5/d
c**d

array([[6.56100e+03, 3.27680e+04, 1.17649e+05],
       [1.00000e+00, 2.56000e+02, 2.18700e+03]])

In [ ]:
print(a[0])
print([3])
print([0,0])
print(c[0,1])

6
[3]
[0, 0]
8.0


In [ ]:
d[1, 0:2]

array([9., 8.])

In [ ]:
e=np.array([[10,11,12],[13,14,15],[16,17,18],[19,20,21]])
print(e)
# slicing
print(e[:3,:2])

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]]
[[10 11]
 [13 14]
 [16 17]]


In [ ]:
# integer indexing
e[[2,0,3,1],[2,1,0,2]]

array([18, 11, 19, 15])

In [ ]:
e[e>15]

array([16, 17, 18, 19, 20, 21])